# Types
TYPE_STATUS_EVENT = 1
TYPE_STATUS_PERSON = 2
TYPE_STATUS_INVITATION = 3

TYPE_COMMENT_EVENT = 10

TYPE_TEAM_DEFAULT = 20

# Statues
STATUS_EVENT_DRAFT = 1
STATUS_EVENT_RELEASED = 2
STATUS_EVENT_COMPLETED = 3

STATUS_PERSON_ACTIVE = 4
STATUS_PERSON_INACTIVE = 5

STATUS_INVITATION_ACCEPTED = 6
STATUS_INVITATION_TENTATIVE = 7
STATUS_INVITATION_DECLINED = 8
STATUS_INVITATION_NO_RESPONSE = 9

STATUS_EVENT_CANCELLED = 10

# Users
USER_SYSTEM = 0

# Groups
GROUP_ALL = 0
